---
- name: Check kernel version and IP address
  hosts: all
  gather_facts: yes
  vars:
    required_kernel: "kernel-5.14.0-427.el9"
    required_ip: "172.25.2.1"
  tasks:
    - name: Get installed kernel version
      ansible.builtin.shell: uname -r
      register: kernel_version
      changed_when: false

    - name: Get IP address of eth_link0
      ansible.builtin.command: ip addr show eth_link0
      register: ip_addr_output
      changed_when: false

    - name: Parse IP address from command output
      set_fact:
        installed_ip: "{{ (ip_addr_output.stdout | regex_search('inet (\\d+\\.\\d+\\.\\d+\\.\\d+)/', '\\1')) }}"

    - name: Display comparison results in columns
      ansible.builtin.debug:
        msg: |
          | Item   | Required             | Installed           | Status   |
          |--------|----------------------|---------------------|----------|
          | Kernel | {{ required_kernel }} | kernel-{{ kernel_version.stdout }} | {% if ("kernel-" + kernel_version.stdout == required_kernel) %}Succeed{% else %}Failed{% endif %} |
          | IP     | {{ required_ip }}    | {{ installed_ip }}   | {% if installed_ip == required_ip %}Succeed{% else %}Failed{% endif %} |

